import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>4.6 BILLION WON AWAITS </h1>
        <p className={styles.description}>What are you waiting for</p>
        <Link href="/gamedetailsuit">
          <a href="/gamedetailsuit" className={styles.btn}>Play Game </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p>© Binar Kelompok 3. All rights reserved.</p>
      </footer>
    </div>
  );
}
